# Generated by Copilot for homestay features fields
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0002_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="homestay",
            name="accommodation_type",
            field=models.CharField(
                max_length=32,
                choices=[
                    ("Private Room", "Private Room"),
                    ("Entire House", "Entire House"),
                    ("Shared Room", "Shared Room"),
                ],
                default="Private Room",
            ),
        ),
        migrations.AddField(
            model_name="homestay",
            name="max_guests",
            field=models.CharField(
                max_length=16,
                choices=[
                    ("1-3 People", "1-3 People"),
                    ("4-6 People", "4-6 People"),
                    ("7+ People", "7+ People"),
                ],
                default="4-6 People",
            ),
        ),
        migrations.AddField(
            model_name="homestay",
            name="meals_included",
            field=models.CharField(
                max_length=32,
                choices=[
                    ("None", "None"),
                    ("Breakfast", "Breakfast"),
                    ("Breakfast & Dinner", "Breakfast & Dinner"),
                    ("All Meals", "All Meals"),
                ],
                default="Breakfast & Dinner",
            ),
        ),
        migrations.AddField(
            model_name="homestay",
            name="wifi_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homestay",
            name="parking",
            field=models.CharField(
                max_length=16,
                choices=[
                    ("None", "None"),
                    ("Limited", "Limited"),
                    ("Available", "Available"),
                ],
                default="Limited",
            ),
        ),
        migrations.AddField(
            model_name="homestay",
            name="pet_friendly",
            field=models.BooleanField(default=False),
        ),
    ]
