# Generated by Copilot for homestay max_guests data migration
from django.db import migrations

def convert_max_guests(apps, schema_editor):
    Homestay = apps.get_model('tourism', 'Homestay')
    for homestay in Homestay.objects.all():
        val = homestay.max_guests
        if isinstance(val, int):
            homestay.max_guests = val
        elif val == '1-3 People':
            homestay.max_guests = 3
        elif val == '4-6 People':
            homestay.max_guests = 6
        elif val == '7+ People':
            homestay.max_guests = 7
        else:
            homestay.max_guests = 4
        homestay.save()

class Migration(migrations.Migration):
    dependencies = [
        ("tourism", "0008_homestay_features"),
    ]

    operations = [
        migrations.RunPython(convert_max_guests),
    ]
