# Generated by Django 5.2.5 on 2025-09-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_convert_max_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestay',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='meals_included',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='parking',
        ),
        migrations.AddField(
            model_name='homestay',
            name='beach_front',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homestay',
            name='videoke_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='max_guests',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
