# Generated by Django 5.2.5 on 2025-09-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_remove_homestay_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
