# Generated by Django 5.2.5 on 2025-09-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_booking_contact_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
