# Generated by Django 5.2.5 on 2025-10-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_homestayfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestayfeature',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='homestayfeature',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
