# Generated by Django 5.2.5 on 2025-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_remove_homestayfeature_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='is_under_maintenance',
            field=models.BooleanField(default=False, help_text='True = Under Maintenance, False = Not Under Maintenance'),
        ),
    ]
