# Generated by Django 5.2.5 on 2025-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_remove_room_status_room_is_under_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('registration', 'Registration'), ('calendar', 'Calendar')], default='registration', max_length=20),
        ),
    ]
